export const UNIVERSITY_COURSES = {
  "B.Tech": [
    "Computer Science & Engineering (CSE)",
    "CSE (AI & Data Science)",
    "CSE (Cyber Security)",
    "AI & Machine Learning",
    "Mining Engineering",
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Cement Technology",
    "Ceramics & Cement Technology",
    "Agricultural Engineering",
    "Food Technology",
    "Biotechnology",
  ],
  "B.Tech (Lateral Entry)": [
    "CSE",
    "Civil Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Mining Engineering",
    "Cement Technology",
    "Food Technology",
    "Agricultural Engineering",
  ],
  "M.Tech": [
    "Computer Science and Engineering",
    "Mining Engineering",
    "Mechanical Engineering",
    "Agricultural Engineering",
    "Biotechnology",
  ],
  "Polytechnic Diploma": [
    "Computer Science And Engineering",
    "Mining Engineering",
    "Mine Surveying",
    "Civil Engineering",
    "Electrical Engineering",
    "Mechanical Engineering",
    "Cement Technology",
    "Food Technology",
    "Agricultural Engineering",
    "Fashion Design",
  ],
  "Polytechnic Diploma (Lateral Entry)": [
    "Civil Engineering",
    "Electrical Engineering",
    "Cement Technology",
    "Agricultural Engineering",
  ],
  "BCA": [
    "BCA (Hons)",
    "BCA (Hons) AI & Machine Learning",
  ],
  "MCA": [
    "Master of Computer Applications",
  ],
  "B.Sc.": [
    "Computer Science (CS)",
    "Information Technology (IT) Hons",
    "Agriculture (Hons)",
    "Horticulture (Hons)",
    "Food Technology",
    "Biotechnology (Hons)",
    "Microbiology",
    "Geology",
    "Math (Hons)",
    "Math in Biology",
    "Seed Technology",
  ],
  "M.Sc.": [
    "Computer Science",
    "Food Technology",
    "Biotechnology",
    "Microbiology",
    "Environmental Science",
    "Chemistry",
    "Physics",
    "Mathematics",
    "Yoga Science",
    "Agriculture (Agronomy)",
    "Agriculture (Soil Science)",
    "Agriculture (Genetics)",
    "Agriculture (Plant Pathology)",
    "Agriculture (Fruit Science)",
    "Agriculture (Chemistry)",
  ],
  "Management": [
    "BBA (Hons)",
    "BBA (Tourism & Hotel Mgmt)",
    "MBA (General)",
    "MBA (Logistics & Supply Chain Management)",
    "MBA (Production & Operation Management)",
    "MBA (Executive)",
    "MBA (Retail Management)",
    "MBA (Human Resource Management)",
    "MBA (Information Technology & Systems Management)",
    "MBA (Marketing)",
    "MBA (Rural Management)",
    "MBA (Banking & Insurance)",
    "MBA (Finance)",
    "MBA (Tourism And Hospitality Management)",
    "MBA (Agri-Business Management)",
  ],
  "Commerce": [
    "B.Com (Computer Application)",
    "B.Com (Economics)",
    "B.Com (Financial Mgmt)",
    "B.Com (Hons)",
    "B.Com (Corporate Accounting Practice - CAP)",
    "B.Com (Corporate Secretarial Practice - CSP)",
    "M.Com",
  ],
  "Pharmacy": [
    "D.Pharma",
    "B.Pharma",
    "M.Pharma (Pharmaceutics)",
    "M.Pharma (Pharmaceutical Chemistry)",
  ],
  "Agriculture": [
    "B.Sc. (Hons) Agriculture",
    "B.Tech Agricultural Engg",
    "M.Sc. Agronomy",
    "M.Sc. Soil Science",
    "M.Sc. Plant Pathology",
    "M.Sc. Fruit Science",
    "M.Sc. Agriculture Chemistry",
  ],
  "B.A. (Bachelor of Arts)": [
    "Computer Applications",
    "Economics",
    "English Literature",
    "Fashion Design",
    "History",
    "Political Science",
    "Public Administration",
    "Sociology",
  ],
  "M.A. (Master of Arts)": [
    "Public Administration",
    "Political Science",
    "Economics",
    "Yoga Science",
  ],
  "Law": [
    "LLB",
    "BBA LLB",
    "BA LLB",
    "B.Com LLB",
    "LLM",
  ],
  "Education": [
    "B.Ed",
    "Ph.D in Education",
  ],
  "Paramedical": [
    "Bachelor of Medical Laboratory Technology (BMLT)",
    "Bachelor of Physiotherapy (B.P.T.)",
  ],
  "Design": [
    "B.Des (Design)",
  ],
  "PG Diploma": [
    "PGDCA",
    "PG Diploma in Cyber Security and Digital Forensics",
  ],
  "Ph.D": [
    "Mining Engineering",
    "Mathematics",
    "Management",
    "Education",
  ],
};
